/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.panelesInteriores;

/**
 *
 * @author mario
 */
public class AñadirDatos extends javax.swing.JPanel {

    /**
     * Creates new form AñadirDatos
     */
    public AñadirDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AñadirFor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        AñadirLoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AñadirUbi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AñadirRie = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AñadirSub = new javax.swing.JTextField();
        BSub = new javax.swing.JButton();
        BUbi = new javax.swing.JButton();
        BRie = new javax.swing.JButton();
        BFor = new javax.swing.JButton();
        BLoc = new javax.swing.JButton();

        setBackground(new java.awt.Color(222, 255, 238));
        setPreferredSize(new java.awt.Dimension(1046, 656));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Formato");
        add(jLabel1);
        jLabel1.setBounds(220, 170, 90, 20);
        add(AñadirFor);
        AñadirFor.setBounds(460, 170, 190, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Localización");
        add(jLabel2);
        jLabel2.setBounds(220, 220, 140, 20);
        add(AñadirLoc);
        AñadirLoc.setBounds(460, 220, 190, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Ubicación");
        add(jLabel3);
        jLabel3.setBounds(220, 270, 130, 20);
        add(AñadirUbi);
        AñadirUbi.setBounds(460, 270, 190, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Riesgos");
        add(jLabel4);
        jLabel4.setBounds(220, 320, 90, 30);
        add(AñadirRie);
        AñadirRie.setBounds(460, 320, 190, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Subcategoría o tipo");
        add(jLabel5);
        jLabel5.setBounds(220, 370, 230, 30);
        add(AñadirSub);
        AñadirSub.setBounds(460, 370, 190, 22);

        BSub.setBackground(new java.awt.Color(0, 102, 102));
        BSub.setForeground(new java.awt.Color(255, 255, 255));
        BSub.setText("Añadir");
        add(BSub);
        BSub.setBounds(700, 370, 80, 20);

        BUbi.setBackground(new java.awt.Color(0, 102, 102));
        BUbi.setForeground(new java.awt.Color(255, 255, 255));
        BUbi.setText("Añadir");
        add(BUbi);
        BUbi.setBounds(700, 270, 80, 20);

        BRie.setBackground(new java.awt.Color(0, 102, 102));
        BRie.setForeground(new java.awt.Color(255, 255, 255));
        BRie.setText("Añadir");
        add(BRie);
        BRie.setBounds(700, 320, 80, 20);

        BFor.setBackground(new java.awt.Color(0, 102, 102));
        BFor.setForeground(new java.awt.Color(255, 255, 255));
        BFor.setText("Añadir");
        add(BFor);
        BFor.setBounds(700, 170, 80, 20);

        BLoc.setBackground(new java.awt.Color(0, 102, 102));
        BLoc.setForeground(new java.awt.Color(255, 255, 255));
        BLoc.setText("Añadir");
        add(BLoc);
        BLoc.setBounds(700, 220, 80, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AñadirFor;
    private javax.swing.JTextField AñadirLoc;
    private javax.swing.JTextField AñadirRie;
    private javax.swing.JTextField AñadirSub;
    private javax.swing.JTextField AñadirUbi;
    private javax.swing.JButton BFor;
    private javax.swing.JButton BLoc;
    private javax.swing.JButton BRie;
    private javax.swing.JButton BSub;
    private javax.swing.JButton BUbi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
