/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.popUp;

import com.mycompany.Clases.Materiales;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Mario
 */
public class PopUpM extends javax.swing.JFrame {

    /**
     * Creates new form popUp
     */
    public PopUpM(Materiales m) {
        initComponents();
        this.setResizable(false);
        this.pack();
        try {
            this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/quimica.png")));
        } catch (Exception e) {
            e.printStackTrace();
        }
        NomTF.setEditable(false);

        NomTF.setEditable(false);
        NomTF.setFocusable(false);


        CanTF.setEditable(false);
        CanTF.setFocusable(false);

        SubTF.setEditable(false);
        SubTF.setFocusable(false);

        LocTF.setEditable(false);
        LocTF.setFocusable(false);

        UbiTF.setEditable(false);
        UbiTF.setFocusable(false);

        StoTF.setEditable(false);
        StoTF.setFocusable(false);

        NSeTF.setEditable(false);
        NSeTF.setFocusable(false);

        FecTF.setEditable(false);
        FecTF.setFocusable(false);

        DesTF.setEditable(false);
        DesTF.setFocusable(false);

        NomTF.setText(m.getNombre());

        CanTF.setText(String.valueOf(m.getCantidad()));
        SubTF.setText(m.getSubtipo());
        LocTF.setText(m.getAlmacen());
        UbiTF.setText(m.getUbicacion());
        StoTF.setText(String.valueOf(m.getStock_minimo()));
        NSeTF.setText(m.getNumero_serie());
        FecTF.setText(m.getFecha_compra());
        DesTF.setText(m.getDescripcion());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FecTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CanTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        NomTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DesTF = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        SubTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        NSeTF = new javax.swing.JTextField();
        StoTF = new javax.swing.JTextField();
        UbiTF = new javax.swing.JTextField();
        LocTF = new javax.swing.JTextField();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(801, 816));

        jPanel1.setBackground(new java.awt.Color(44, 171, 182));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DETALLES DEL PRODUCTO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 100);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nº Serie");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(460, 370, 190, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Localización");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(460, 160, 130, 30);
        jPanel1.add(FecTF);
        FecTF.setBounds(170, 260, 190, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 160, 80, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Descripción");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 470, 100, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Ubicación");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(460, 230, 140, 25);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Cantidad");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(170, 300, 80, 25);
        jPanel1.add(CanTF);
        CanTF.setBounds(170, 330, 190, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Fecha de Compra");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(170, 230, 150, 25);

        NomTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomTFActionPerformed(evt);
            }
        });
        jPanel1.add(NomTF);
        NomTF.setBounds(170, 190, 190, 30);

        DesTF.setColumns(20);
        DesTF.setRows(5);
        jScrollPane1.setViewportView(DesTF);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(290, 520, 234, 86);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Stock Mínimo");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(460, 300, 190, 25);
        jPanel1.add(SubTF);
        SubTF.setBounds(170, 410, 190, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Subcategoría o tipo");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(170, 370, 190, 25);
        jPanel1.add(NSeTF);
        NSeTF.setBounds(460, 410, 190, 30);
        jPanel1.add(StoTF);
        StoTF.setBounds(460, 330, 190, 30);
        jPanel1.add(UbiTF);
        UbiTF.setBounds(460, 260, 190, 30);
        jPanel1.add(LocTF);
        LocTF.setBounds(460, 190, 190, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomTFActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CanTF;
    private javax.swing.JTextArea DesTF;
    private javax.swing.JTextField FecTF;
    private javax.swing.JTextField LocTF;
    private javax.swing.JTextField NSeTF;
    private javax.swing.JTextField NomTF;
    private javax.swing.JTextField StoTF;
    private javax.swing.JTextField SubTF;
    private javax.swing.JTextField UbiTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
