/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.popUp;

import com.mycompany.Clases.Quimico;

import javax.swing.*;
import java.awt.*;
import java.net.URL;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * @author Mario
 */
public class PopUpR extends javax.swing.JFrame {

    /**
     * Creates new form popUp
     */
    public PopUpR(Quimico q) {
        initComponents();
        this.pack();
        try {
            this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/quimica.png")));
        } catch (Exception e) {
            e.printStackTrace();
        }
        this.setResizable(false);

        GraTF.setEditable(false);
        GraTF.setFocusable(false);

        NomTF.setEditable(false);
        NomTF.setFocusable(false);

        ForTF.setEditable(false);
        ForTF.setFocusable(false);

        CanTF.setEditable(false);
        CanTF.setFocusable(false);

        FecTF.setEditable(false);
        FecTF.setFocusable(false);

        LocTF.setEditable(false);
        LocTF.setFocusable(false);

        UbiTF.setEditable(false);
        UbiTF.setFocusable(false);

        StoTF.setEditable(false);
        StoTF.setFocusable(false);

        FecTF.setEditable(false);
        FecTF.setFocusable(false);

        //hago que el boton de siguiente no esté visible
        jButton1.setVisible(false);
        //añado el primer pictograma
        URL url = getClass().getResource("/" + q.getPictogramas().get(0).getRuta());
        ImageIcon icon = new ImageIcon(url);
        PicJL.setIcon(icon);
        //si hay mas de un pictograma, activo el boton de siguiente
        if (q.getPictogramas().size() > 0) {
            jButton1.setVisible(true);
        }
        AtomicInteger i = new AtomicInteger(1);
        //añade un listener al boton para que al hacer click se cambie el pictograma
        jButton1.addActionListener(e -> {
            //va avanzando por los pictogramas
            if (i.get() == q.getPictogramas().size()) {
                i.set(0);
            }
            URL url1 = getClass().getResource("/" + q.getPictogramas().get(i.get()).getRuta());
            ImageIcon icon1 = new ImageIcon(url1);
            PicJL.setIcon(icon1);
            i.set(i.get() + 1);


        });


        //añado los datos del quimico a los campos de texto

        NomTF.setText(q.getNombre());
        ForTF.setText(q.getFormato());
        CanTF.setText(String.valueOf(q.getCantidad()));
        LocTF.setText(q.getAlmacen());
        UbiTF.setText(q.getUbicacion());
        StoTF.setText(String.valueOf(q.getStock_minimo()));
        FecTF.setText(q.getFecha_caducidad());
        GraTF.setText(q.getPureza());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LocTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ForTF = new javax.swing.JTextField();
        StoTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        UbiTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        FecTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        PicJL = new javax.swing.JLabel();
        NomTF = new javax.swing.JTextField();
        CanTF = new javax.swing.JTextField();
        GraTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 171, 182));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DETALLES DEL PRODUCTO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 100);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Ubicación");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(460, 140, 160, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 140, 80, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Cantidad");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 280, 80, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Stock Mínimo");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(460, 350, 190, 25);
        jPanel1.add(LocTF);
        LocTF.setBounds(150, 380, 190, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Formato");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(150, 210, 80, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Localización");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 350, 130, 30);

        ForTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForTFActionPerformed(evt);
            }
        });
        jPanel1.add(ForTF);
        ForTF.setBounds(150, 240, 190, 30);
        jPanel1.add(StoTF);
        StoTF.setBounds(460, 380, 190, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Riesgos");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(350, 470, 70, 25);
        jPanel1.add(UbiTF);
        UbiTF.setBounds(460, 170, 190, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Grado de Pureza");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(460, 210, 190, 25);
        jPanel1.add(FecTF);
        FecTF.setBounds(460, 310, 190, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Fecha de Caducidad");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(460, 280, 190, 25);
        jPanel1.add(PicJL);
        PicJL.setBounds(260, 500, 250, 250);

        NomTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomTFActionPerformed(evt);
            }
        });
        jPanel1.add(NomTF);
        NomTF.setBounds(150, 170, 190, 30);
        jPanel1.add(CanTF);
        CanTF.setBounds(150, 310, 190, 30);
        jPanel1.add(GraTF);
        GraTF.setBounds(460, 240, 190, 30);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Siguiente");
        jPanel1.add(jButton1);
        jButton1.setBounds(580, 720, 100, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ForTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ForTFActionPerformed

    private void NomTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomTFActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CanTF;
    private javax.swing.JTextField FecTF;
    private javax.swing.JTextField ForTF;
    private javax.swing.JTextField GraTF;
    private javax.swing.JTextField LocTF;
    private javax.swing.JTextField NomTF;
    private javax.swing.JLabel PicJL;
    private javax.swing.JTextField StoTF;
    private javax.swing.JTextField UbiTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
