/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chemify;

import com.mycompany.Clases.SistemaAlertasStock;
import com.mycompany.panelesInteriores.*;

import java.awt.*;

/**
 *
 * @author mario
 */
public class TeacherWindow extends javax.swing.JFrame {

    /**
     * Creates new form TeacherWindow
     */
    public TeacherWindow() {
        this.setVisible(true);
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        Buscar b1 = new Buscar();
        b1.setSize(1046, 656);
        b1.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(b1, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();

        BBuscar.setEnabled(false);

        PanelMateriales.setVisible(false);
        PanelReactivos.setVisible(false);
        PanelPAuxiliares.setVisible(false);

        PanelMateriales.setBackground(new Color(40, 180, 99));

        // Agrega un listener al botón de alertas
        BLog.addActionListener(e -> {
            // Llama a la función para verificar el stock y enviar alertas
            SistemaAlertasStock.verificarStock();
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTeacher = new javax.swing.JPanel();
        Izquierda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BBuscar = new javax.swing.JButton();
        BInsertar = new javax.swing.JButton();
        BCerrarSesion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BInsertarDatos = new javax.swing.JButton();
        BLog = new javax.swing.JButton();
        GestiónUsuarios = new javax.swing.JButton();
        lupa = new javax.swing.JLabel();
        Derecha = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        PanelMateriales = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelReactivos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PanelPAuxiliares = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHEMIFY");
        setPreferredSize(new java.awt.Dimension(1414, 837));

        PanelTeacher.setPreferredSize(new java.awt.Dimension(1400, 800));
        PanelTeacher.setLayout(null);

        Izquierda.setBackground(new java.awt.Color(0, 102, 102));
        Izquierda.setPreferredSize(new java.awt.Dimension(350, 800));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(222, 255, 238));
        jLabel1.setText("CHEMIFY");

        BBuscar.setBackground(new java.awt.Color(255, 255, 238));
        BBuscar.setText("Buscar");
        BBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarActionPerformed(evt);
            }
        });

        BInsertar.setBackground(new java.awt.Color(255, 255, 238));
        BInsertar.setText("Insertar");
        BInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInsertarActionPerformed(evt);
            }
        });

        BCerrarSesion.setBackground(new java.awt.Color(255, 255, 238));
        BCerrarSesion.setText("Cerrar Sesión");
        BCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCerrarSesionActionPerformed(evt);
            }
        });

        BInsertarDatos.setBackground(new java.awt.Color(255, 255, 238));
        BInsertarDatos.setText("Añadir Datos");
        BInsertarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInsertarDatosActionPerformed(evt);
            }
        });

        BLog.setBackground(new java.awt.Color(255, 255, 238));
        BLog.setText("Consultar Log");
        BLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLogActionPerformed(evt);
            }
        });

        GestiónUsuarios.setBackground(new java.awt.Color(255, 255, 238));
        GestiónUsuarios.setText("Gestionar Usuarios");
        GestiónUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestiónUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IzquierdaLayout = new javax.swing.GroupLayout(Izquierda);
        Izquierda.setLayout(IzquierdaLayout);
        IzquierdaLayout.setHorizontalGroup(
            IzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IzquierdaLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(IzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BCerrarSesion)
                    .addComponent(BLog))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IzquierdaLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(IzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IzquierdaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IzquierdaLayout.createSequentialGroup()
                        .addGroup(IzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BInsertarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lupa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IzquierdaLayout.createSequentialGroup()
                        .addComponent(GestiónUsuarios)
                        .addGap(100, 100, 100))))
        );
        IzquierdaLayout.setVerticalGroup(
            IzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IzquierdaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addGroup(IzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lupa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(BInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(BInsertarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(GestiónUsuarios)
                .addGap(113, 113, 113)
                .addGroup(IzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(BCerrarSesion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BLog)
                .addGap(32, 32, 32))
        );

        PanelTeacher.add(Izquierda);
        Izquierda.setBounds(-10, -10, 350, 810);

        Derecha.setBackground(new java.awt.Color(222, 255, 238));
        Derecha.setPreferredSize(new java.awt.Dimension(1050, 800));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(1050, 123));

        PanelMateriales.setBackground(new java.awt.Color(0, 102, 102));
        PanelMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMaterialesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelMaterialesMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Material");

        javax.swing.GroupLayout PanelMaterialesLayout = new javax.swing.GroupLayout(PanelMateriales);
        PanelMateriales.setLayout(PanelMaterialesLayout);
        PanelMaterialesLayout.setHorizontalGroup(
            PanelMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMaterialesLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(33, 33, 33))
        );
        PanelMaterialesLayout.setVerticalGroup(
            PanelMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMaterialesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelReactivos.setBackground(new java.awt.Color(0, 102, 102));
        PanelReactivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelReactivosMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Reactivo");

        javax.swing.GroupLayout PanelReactivosLayout = new javax.swing.GroupLayout(PanelReactivos);
        PanelReactivos.setLayout(PanelReactivosLayout);
        PanelReactivosLayout.setHorizontalGroup(
            PanelReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReactivosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        PanelReactivosLayout.setVerticalGroup(
            PanelReactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelReactivosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        PanelPAuxiliares.setBackground(new java.awt.Color(0, 102, 102));
        PanelPAuxiliares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelPAuxiliaresMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("P. Auxiliar");

        javax.swing.GroupLayout PanelPAuxiliaresLayout = new javax.swing.GroupLayout(PanelPAuxiliares);
        PanelPAuxiliares.setLayout(PanelPAuxiliaresLayout);
        PanelPAuxiliaresLayout.setHorizontalGroup(
            PanelPAuxiliaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPAuxiliaresLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        PanelPAuxiliaresLayout.setVerticalGroup(
            PanelPAuxiliaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPAuxiliaresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(PanelMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelReactivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPAuxiliares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 591, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 74, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelPAuxiliares, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelReactivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelMateriales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Contenedor.setBackground(new java.awt.Color(222, 255, 238));
        Contenedor.setPreferredSize(new java.awt.Dimension(1050, 668));

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DerechaLayout = new javax.swing.GroupLayout(Derecha);
        Derecha.setLayout(DerechaLayout);
        DerechaLayout.setHorizontalGroup(
            DerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
            .addGroup(DerechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE))
        );
        DerechaLayout.setVerticalGroup(
            DerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DerechaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE))
        );

        PanelTeacher.add(Derecha);
        Derecha.setBounds(340, 0, 1060, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarActionPerformed
        BBuscar.setEnabled(false);
        BInsertar.setEnabled(true);
        BInsertarDatos.setEnabled(true);
        GestiónUsuarios.setEnabled(true);
        Buscar b1 = new Buscar();
        b1.setSize(1050, 668);
        b1.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(b1, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();

        PanelMateriales.setVisible(false);
        PanelReactivos.setVisible(false);
        PanelPAuxiliares.setVisible(false);


    }//GEN-LAST:event_BBuscarActionPerformed

    private void BCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCerrarSesionActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login lg1 = new Login();
        lg1.setVisible(true);
    }//GEN-LAST:event_BCerrarSesionActionPerformed

    private void BInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInsertarActionPerformed
        // TODO add your handling code here:
        BBuscar.setEnabled(true);
        BInsertar.setEnabled(false);
        BInsertarDatos.setEnabled(true);
        GestiónUsuarios.setEnabled(true);
        InsertarMateriales i1 = new InsertarMateriales();
        i1.setSize(1046, 656);
        i1.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(i1, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();

        PanelMateriales.setVisible(true);
        PanelReactivos.setVisible(true);
        PanelPAuxiliares.setVisible(true);

    }//GEN-LAST:event_BInsertarActionPerformed

    private void PanelMaterialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMaterialesMouseClicked
        // TODO add your handling code here:
        PanelMateriales.setBackground(new Color(40, 180, 99));
        PanelReactivos.setBackground(new Color(0, 102, 102));
        PanelPAuxiliares.setBackground(new Color(0, 102, 102));
        InsertarMateriales i1 = new InsertarMateriales();
        i1.setSize(1046, 656);
        i1.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(i1, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();

        PanelMateriales.setVisible(true);
        PanelReactivos.setVisible(true);
        PanelPAuxiliares.setVisible(true);
    }//GEN-LAST:event_PanelMaterialesMouseClicked

    private void PanelReactivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelReactivosMouseClicked
        // TODO add your handling code here:
        PanelReactivos.setBackground(new Color(40, 180, 99));
        PanelPAuxiliares.setBackground(new Color(0, 102, 102));
        PanelMateriales.setBackground(new Color(0, 102, 102));

        InsertarReactivos i2 = new InsertarReactivos();
        i2.setSize(1046, 656);
        i2.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(i2, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();

        PanelMateriales.setVisible(true);
        PanelReactivos.setVisible(true);
        PanelPAuxiliares.setVisible(true);
    }//GEN-LAST:event_PanelReactivosMouseClicked

    private void PanelPAuxiliaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPAuxiliaresMouseClicked
        // TODO add your handling code here:
        PanelPAuxiliares.setBackground(new Color(40, 180, 99));
        PanelMateriales.setBackground(new Color(0, 102, 102));
        PanelReactivos.setBackground(new Color(0, 102, 102));

        InsertarPAuxiliares i3 = new InsertarPAuxiliares();
        i3.setSize(1046, 656);
        i3.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(i3, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();

        PanelMateriales.setVisible(true);
        PanelReactivos.setVisible(true);
        PanelPAuxiliares.setVisible(true);


    }//GEN-LAST:event_PanelPAuxiliaresMouseClicked

    private void PanelMaterialesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMaterialesMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_PanelMaterialesMouseExited

    private void BInsertarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInsertarDatosActionPerformed
        // TODO add your handling code here:
        BBuscar.setEnabled(true);
        BInsertar.setEnabled(true);
        BInsertarDatos.setEnabled(false);
        GestiónUsuarios.setEnabled(true);
        AñadirDatos a3 = new AñadirDatos();
        a3.setSize(1046, 656);
        a3.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(a3, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();

        PanelMateriales.setVisible(false);
        PanelReactivos.setVisible(false);
        PanelPAuxiliares.setVisible(false);

    }//GEN-LAST:event_BInsertarDatosActionPerformed

    private void BLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BLogActionPerformed

    private void GestiónUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestiónUsuariosActionPerformed
        // TODO add your handling code here:
        BBuscar.setEnabled(true);
        BInsertar.setEnabled(true);
        BInsertarDatos.setEnabled(true);
        GestiónUsuarios.setEnabled(false);
        
        modificarUsuario u3 = new modificarUsuario();
        u3.setSize(1046, 656);
        u3.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(u3, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
        PanelMateriales.setVisible(false);
        PanelReactivos.setVisible(false);
        PanelPAuxiliares.setVisible(false);
    }//GEN-LAST:event_GestiónUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBuscar;
    private javax.swing.JButton BCerrarSesion;
    private javax.swing.JButton BInsertar;
    private javax.swing.JButton BInsertarDatos;
    private javax.swing.JButton BLog;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JPanel Derecha;
    private javax.swing.JButton GestiónUsuarios;
    private javax.swing.JPanel Izquierda;
    private javax.swing.JPanel PanelMateriales;
    private javax.swing.JPanel PanelPAuxiliares;
    private javax.swing.JPanel PanelReactivos;
    private javax.swing.JPanel PanelTeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lupa;
    // End of variables declaration//GEN-END:variables
}
